### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by ljl7123** [christopher-wolff23/java-pong#14]
Installation instructions could be added to the README.

@christopher-wolff23 Could you explain the following:
1. What prerequisites are needed?
2. How to install the project?

Thanks in advance!

**Comment by ljl7123** [comment]
@christopher-wolff23 Thanks, I'll write the installation section!

**Comment by christopher-wolff23** [comment]
@ljl7123 there is now an executable .jar and the game actually runs.
