### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by ljl7123** [christopher-wolff23/java-pong#3]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision. Existing style guidelines would be taken into account. The following is one of the resources I would be using:

https://jacobian.org/writing/technical-style/

Would anyone mind if I propose edits to documentation in this repository? It would really help me out!

**Comment by christopher-wolff23** [comment]
I definitely wouldn't mind, but I don't think you'll find much documentation in this repo :)

**Comment by ljl7123** [comment]
Thanks @christopher-wolff23 !

**Comment by christopher-wolff23** [comment]
@ljl7123 No problem, let me know if you have any questions. The code is pretty simple! I'd be happy to walk you through anything.

**Comment by ljl7123** [comment]
Awesome! Actually, could you give me a high level description of your app?  I understand that it's a version of the Pong game, (table tennis sports game featuring simple two-dimensional graphics) but I'm not quite sure about:
1. The AI model that's mentioned in the README
2. Does a menu show up at the beginning of the game for a list of options?
3. Can the player repeatedly replay the game?

I was hoping to use this information to flesh out the README, if that sounds okay?

Thanks in advance!

**Comment by ljl7123** [comment]
Thanks @christopher-wolff23 ! I'll make a PR for the README introduction.

**Comment by ljl7123** [comment]
(For my assignment, I need to create a new issue for each PR I make. I'll make a PR for each individual section that I edit/add in the README.)

**Comment by christopher-wolff23** [comment]
@ljl7123 No problem!

**Comment by ljl7123** [comment]
Made the PR :)
